[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://rileywatch.onrender.com/api"
  VITE_TMDB_KEY = "your_tmdb_key_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
